


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal


# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
    
#IgaIgaNewsBundle:
#    resource: "@IgaNewsBundle/Controller/UniversityController.ph"
#    type:     annotation
#    prefix:   /

UniversityController:
    resource: "@IgaUniverseBundle/Controller/UniversityController.php"
    type:     annotation
    prefix:   /

GradeController:
    resource: "@IgaUniverseBundle/Controller/GradeController.php"
    type:     annotation
    prefix:   /

Career:
    resource: "@IgaUniverseBundle/Controller/CareerController.php"
    type:     annotation
    prefix:   /

FileTypeController:
    resource: "@IgaUniverseBundle/Controller/FileTypeController.php"
    type:     annotation
    prefix:   /


DefaultController:
    resource: "@IgaUniverseBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /
  

SubjectController:
    resource: "@IgaUniverseBundle/Controller/SubjectController.php"
    type:     annotation
    prefix:   /
    